version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 10
    # Group all minor and patch updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Allow security updates
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "fix"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    reviewers:
      - "azure/static-web-apps-cli-maintainers"
    
  # Enable version updates for npm in docs
  - package-ecosystem: "npm"
    directory: "/docs/www"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 5
    groups:
      docs-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(docs)"
      include: "scope"
    labels:
      - "dependencies"
      - "documentation"
      
  # Enable security updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci"