name: Deploy CLI docs
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: git config --global user.email "github@wassim.dev"
      - run: git config --global user.name "Wassim Chegham"
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: "deploy docs"
        run: |
          cd docs/www/
          npm ci
          npm run deploy
        env:
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
          GIT_USER: ${{ github.actor }}
