name: Deploy CLI docs
on:
  push:
    branches: [ga]  # TODO: update to main after GA

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: '16.x'
      - name: "deploy docs"
        run: |
          npm ci
          npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.SWA_CLI_DEPLOY_DOCS_GH_PAGES }}
